import Sidebar from '@/components/Sidebar'
import '../globals.css'
import Header from '@/components/Header'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
       
      <body className='pl-2 pr-2 ' >
         <Header />
         <Sidebar/>
        {children}</body>
    </html>
  )
}
